

# import os
# # import logging
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder
# from nltk.stem.porter import PorterStemmer
# from nltk.corpus import stopwords
# import string
# import nltk
# nltk.download('stopwords')
# ps = PorterStemmer()



# import nltk
# from nltk.tokenize import word_tokenize


# nltk.download('punkt_tab')
# def transform_text(text):
#     ps = PorterStemmer()
#     text = text.lower()
#     text = word_tokenize(text)
#     text = [word for word in text if word.isalnum()]
#     text = [word for word in text if word not in stopwords.words('english') and word not in string.punctuation]
#     text = [ps.stem(word) for word in text]
#     return " ".join(text)

